import jwt from'jsonwebtoken';import request from'supertest';import{createApp}from'../src/app.js'
const id=n=>n.toString(16).padStart(24,'0'),doctorId=id(10),facilityId=id(20),serviceId=id(30),userId=id(40)
void serviceId
const isActive=true
const query=value=>({populate:async()=>value,select:async()=>value,then:(resolve,reject)=>Promise.resolve(value).then(resolve,reject)})
// eslint-disable-next-line no-unused-vars
function setup(role='ADMIN',active=true,linked=true){const user={id:userId,_id:userId,role,isActive};const users={findById:async value=>value===id(99)?{_id:id(99),role:'DOCTOR'}:user,findOne:()=>query(null)};const facility={_id:facilityId,name:'City Hospital',district:'Colombo',facilityIds:[facilityId],isActive:true};const doctor={_id:doctorId,userId:linked?userId:undefined,name:'Dr Test',specialization:'GENERAL_PRACTITIONER',facilityIds:[facility],healthServiceIds:[],supportedLanguages:['en'],consultationType:'IN_PERSON',isActive:true};const doctors={find:()=>query([doctor]),findOne:filter=>query(filter.userId&&!linked?null:doctor),findOneAndUpdate:async(_filter,data)=>({...doctor,...data}),create:async data=>({...doctor,...data})};const facilities={find:()=>query([]),findOne:async()=>facility,findOneAndUpdate:async()=>facility,create:async data=>({_id:facilityId,...data}),countDocuments:async filter=>filter._id.$in.length};const services={find:async()=>[],findOne:async()=>null,countDocuments:async filter=>filter._id.$in.length};const schedule={_id:id(50),doctorId:doctor,facilityId:facility,date:'2099-09-10',startTime:'09:00',endTime:'10:00',slotDurationMinutes:20,isActive:true};const schedules={find:()=>query([schedule]),findOne:filter=>query(filter.startTime?null:schedule),findOneAndUpdate:async(_filter,data)=>({...schedule,...data}),create:async data=>({...schedule,...data})};const appointments={find:async()=>[]};const app=createApp({userModel:users,healthServiceModel:services,facilityModel:facilities,doctorModel:doctors,scheduleModel:schedules,appointmentModel:appointments});const token=jwt.sign({role},process.env.JWT_SECRET,{subject:userId,expiresIn:'1h'});return{app,token}}
const doctorBody={name:'Dr Test',specialization:'GENERAL_PRACTITIONER',facilityIds:[facilityId],healthServiceIds:[],supportedLanguages:['en'],consultationType:'IN_PERSON'}
const scheduleBody={doctorId,facilityId,date:'2099-09-10',startTime:'09:00',endTime:'10:00',slotDurationMinutes:20}
test('public can list and read active doctors safely',async()=>{const{app}=setup();const list=await request(app).get('/api/v1/doctors');expect(list.status).toBe(200);expect(list.body.data.count).toBe(1);expect(list.body.data.items[0]).not.toHaveProperty('userId');expect((await request(app).get(`/api/v1/doctors/${doctorId}`)).status).toBe(200)})
test.each(['PATIENT','DOCTOR'])('%s cannot create arbitrary doctor profiles',async role=>{const{app,token}=setup(role);expect((await request(app).post('/api/v1/doctors').set('Authorization',`Bearer ${token}`).send(doctorBody)).status).toBe(403)})
test('unauthenticated cannot create doctor',async()=>{expect((await request(setup().app).post('/api/v1/doctors').send(doctorBody)).status).toBe(401)})
test('ADMIN can create, update, and deactivate doctors',async()=>{const{app,token}=setup();expect((await request(app).post('/api/v1/doctors').set('Authorization',`Bearer ${token}`).send(doctorBody)).status).toBe(201);expect((await request(app).patch(`/api/v1/doctors/${doctorId}`).set('Authorization',`Bearer ${token}`).send({bio:'Updated'})).status).toBe(200);expect((await request(app).delete(`/api/v1/doctors/${doctorId}`).set('Authorization',`Bearer ${token}`)).status).toBe(200)})
test('DOCTOR gets own profile while PATIENT is denied',async()=>{const doctorSetup=setup('DOCTOR');expect((await request(doctorSetup.app).get('/api/v1/doctors/me').set('Authorization',`Bearer ${doctorSetup.token}`)).status).toBe(200);const patient=setup('PATIENT');expect((await request(patient.app).get('/api/v1/doctors/me').set('Authorization',`Bearer ${patient.token}`)).status).toBe(403)})
test('DOCTOR without linked profile gets controlled 404',async()=>{const{app,token}=setup('DOCTOR',true,false);const response=await request(app).get('/api/v1/doctors/me').set('Authorization',`Bearer ${token}`);expect(response.status).toBe(404);expect(response.body.error.code).toBe('DOCTOR_PROFILE_NOT_FOUND')})
test('only ADMIN can mutate schedules',async()=>{for(const role of['PATIENT','DOCTOR']){const{app,token}=setup(role);expect((await request(app).post('/api/v1/schedules').set('Authorization',`Bearer ${token}`).send(scheduleBody)).status).toBe(403)}const{app,token}=setup('ADMIN');expect((await request(app).post('/api/v1/schedules').set('Authorization',`Bearer ${token}`).send(scheduleBody)).status).toBe(201)})
test('DOCTOR schedule view is resolved from authenticated user',async()=>{const{app,token}=setup('DOCTOR');const response=await request(app).get('/api/v1/schedules/mine').set('Authorization',`Bearer ${token}`);expect(response.status).toBe(200);expect(response.body.data.count).toBe(1)})
test('availability is public and contains generated slots',async()=>{const response=await request(setup().app).get(`/api/v1/doctors/${doctorId}/availability?date=2099-09-10`);expect(response.status).toBe(200);expect(response.body.data.schedules[0].availableSlots).toEqual(['09:00','09:20','09:40'])})
test.each(['/api/v1/doctors/bad','/api/v1/doctors?facility=bad',`/api/v1/doctors/${doctorId}/availability?date=bad`])('malformed doctor request %s is rejected safely',async path=>{const response=await request(setup().app).get(path);expect(response.status).toBe(422);expect(response.body.success).toBe(false)})
