export const FACILITY_TYPES=['HOSPITAL','CLINIC','MEDICAL_CENTRE','SPECIALIST_CENTRE','DENTAL_CLINIC','EYE_CLINIC','MENTAL_HEALTH_CENTRE','OTHER']
export const DISTRICTS=['Ampara','Anuradhapura','Badulla','Batticaloa','Colombo','Galle','Gampaha','Hambantota','Jaffna','Kalutara','Kandy','Kegalle','Kilinochchi','Kurunegala','Mannar','Matale','Matara','Monaragala','Mullaitivu','Nuwara Eliya','Polonnaruwa','Puttalam','Ratnapura','Trincomalee','Vavuniya']
export const LANGUAGES=['en','si','ta']
export const SPECIALIZATIONS=['GENERAL_PRACTITIONER','PEDIATRICIAN','DENTIST','DERMATOLOGIST','CARDIOLOGIST','PSYCHIATRIST','ENT_SPECIALIST','OPHTHALMOLOGIST','GYNECOLOGIST','ORTHOPEDIC_SPECIALIST','OTHER']
export const CONSULTATION_TYPES=['IN_PERSON']
export const SLOT_DURATIONS=[15,20,30,45,60]
export const APPOINTMENT_STATUSES=['PENDING','CONFIRMED','COMPLETED','CANCELLED']
export const SLOT_RESERVING_STATUSES=['PENDING','CONFIRMED']
