/**
 * Stable error codes for frontend and agent integration.
 *
 * These codes appear in error responses as:
 *   { "success": false, "error": { "code": "<CODE>", "message": "..." } }
 *
 * Do not rename or remove codes without coordinating with frontend and agent teams.
 */
export const ERROR_CODES = Object.freeze({
  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',

  // Authentication
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHENTICATED: 'AUTHENTICATION_REQUIRED', // alias

  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',

  // Conflicts
  CONFLICT: 'CONFLICT',
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  DUPLICATE_SERVICE: 'DUPLICATE_SERVICE',
  DOCTOR_USER_ALREADY_LINKED: 'DOCTOR_USER_ALREADY_LINKED',
  SCHEDULE_OVERLAP: 'SCHEDULE_OVERLAP',
  SLOT_UNAVAILABLE: 'SLOT_UNAVAILABLE',
  ALREADY_CANCELLED: 'ALREADY_CANCELLED',
  APPOINTMENT_COMPLETED: 'APPOINTMENT_COMPLETED',
  APPOINTMENT_NOT_ACTIVE: 'APPOINTMENT_NOT_ACTIVE',

  // Resource state
  INACTIVE_RESOURCE: 'INACTIVE_RESOURCE',
  DOCTOR_PROFILE_NOT_FOUND: 'DOCTOR_PROFILE_NOT_FOUND',

  // Reference validation
  INVALID_ID: 'INVALID_ID',
  INVALID_FACILITY_REFERENCE: 'INVALID_FACILITY_REFERENCE',
  INVALID_SERVICE_REFERENCE: 'INVALID_SERVICE_REFERENCE',
  INVALID_DOCTOR_REFERENCE: 'INVALID_DOCTOR_REFERENCE',
  INVALID_SCHEDULE_REFERENCE: 'INVALID_SCHEDULE_REFERENCE',
  INVALID_DOCTOR_USER: 'INVALID_DOCTOR_USER',
  FACILITY_NOT_ASSIGNED: 'FACILITY_NOT_ASSIGNED',
  SCHEDULE_DOCTOR_MISMATCH: 'SCHEDULE_DOCTOR_MISMATCH',
  SCHEDULE_FACILITY_MISMATCH: 'SCHEDULE_FACILITY_MISMATCH',
  SCHEDULE_DATE_MISMATCH: 'SCHEDULE_DATE_MISMATCH',

  // Scheduling / appointments
  INVALID_DATE: 'INVALID_DATE',
  INVALID_TIME: 'INVALID_TIME',
  PAST_SCHEDULE: 'PAST_SCHEDULE',
  INVALID_SCHEDULE_INTERVAL: 'INVALID_SCHEDULE_INTERVAL',
  INVALID_SLOT_DURATION: 'INVALID_SLOT_DURATION',
  INVALID_APPOINTMENT_DATE: 'INVALID_APPOINTMENT_DATE',
  INVALID_APPOINTMENT_SLOT: 'INVALID_APPOINTMENT_SLOT',
  DOCTOR_CHANGE_NOT_ALLOWED: 'DOCTOR_CHANGE_NOT_ALLOWED',
})
