import { useEffect, useState } from 'react'
import FacilityCard from '../components/facilities/FacilityCard.jsx'
import { getFacilities } from '../features/facilities/facilityService.js'
import { getHealthServices } from '../features/services/healthServiceService.js'
import { DISTRICTS, FACILITY_TYPES, LANGUAGES } from '../utils/domain.js'

const emptyFilters = { district: '', facilityType: '', healthService: '', language: '', emergencyAvailable: '' }
export default function FacilitiesPage() {
  const [filters, setFilters] = useState(emptyFilters); const [applied, setApplied] = useState(emptyFilters); const [data, setData] = useState(null); const [services, setServices] = useState([]); const [error, setError] = useState('')
  useEffect(() => { getHealthServices().then((result) => setServices(result.items)).catch(() => setError('Unable to load health-service filters.')) }, [])
  useEffect(() => { setData(null); setError(''); getFacilities(Object.fromEntries(Object.entries(applied).filter(([, value]) => value !== ''))).then(setData).catch(() => setError('Unable to load healthcare facilities.')) }, [applied])
  const change = (event) => setFilters({ ...filters, [event.target.name]: event.target.value }); const reset = () => { setFilters(emptyFilters); setApplied(emptyFilters) }
  return <section><h1>Healthcare facilities</h1><form className="filters" onSubmit={(event) => { event.preventDefault(); setApplied(filters) }}><label>District<select name="district" value={filters.district} onChange={change}><option value="">All districts</option>{DISTRICTS.map((item) => <option key={item}>{item}</option>)}</select></label><label>Facility type<select name="facilityType" value={filters.facilityType} onChange={change}><option value="">All facility types</option>{FACILITY_TYPES.map((item) => <option value={item} key={item}>{item.replaceAll('_', ' ')}</option>)}</select></label><label>Health service<select name="healthService" value={filters.healthService} onChange={change}><option value="">All services</option>{services.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Language<select name="language" value={filters.language} onChange={change}><option value="">All languages</option>{LANGUAGES.map((item) => <option value={item.code} key={item.code}>{item.label}</option>)}</select></label><label>Emergency capability<select name="emergencyAvailable" value={filters.emergencyAvailable} onChange={change}><option value="">Any</option><option value="true">Listed</option><option value="false">Not listed</option></select></label><div className="filter-actions"><button type="submit">Apply filters</button><button type="button" onClick={reset}>Clear filters</button></div></form>{error && <p role="alert">{error}</p>}{!data && !error ? <p role="status">Loading facilities…</p> : data?.count === 0 ? <p>No active facilities match these filters.</p> : <div className="cards">{data?.items.map((item) => <FacilityCard facility={item} key={item.id} />)}</div>}</section>
}
